[project]
name = "back-end"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
<<<<<<< Updated upstream
dependencies = []
=======
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pydantic>=2.11.7",
    "uvicorn>=0.34.3",
]
>>>>>>> Stashed changes
